import { defineField, defineType } from "sanity";

export default defineType({
  name: "project",
  title: "Portfolio Project",
  type: "document",
  groups: [
    { name: "overview", title: "Overview" },
    { name: "story", title: "Case Study" },
    { name: "gallery", title: "Gallery & Brand" },
    { name: "results", title: "Results & Links" },
  ],
  fields: [
    defineField({
      name: "plateNumber",
      title: "Plate number",
      type: "number",
      group: "overview",
      description: "Catalog number shown on the index (e.g. 1, 2, 3). Controls default ordering.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "title",
      title: "Project title",
      type: "string",
      group: "overview",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "overview",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "client",
      title: "Client",
      type: "string",
      group: "overview",
    }),
    defineField({
      name: "industry",
      title: "Industry / category",
      type: "string",
      group: "overview",
      description: "e.g. Fashion, Logistics, Food & Beverage",
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      group: "overview",
    }),
    defineField({
      name: "featured",
      title: "Featured on homepage",
      type: "boolean",
      group: "overview",
      initialValue: false,
    }),
    defineField({
      name: "coverImage",
      title: "Cover image",
      type: "image",
      group: "overview",
      options: { hotspot: true },
      fields: [{ name: "alt", title: "Alt text", type: "string", validation: (r) => r.required() }],
      validation: (r) => r.required(),
    }),
    defineField({
      name: "summary",
      title: "One-line summary",
      type: "string",
      group: "overview",
      description: "Shown on the index page next to the plate number.",
      validation: (r) => r.max(140),
    }),
    defineField({
      name: "objectives",
      title: "Objectives",
      type: "array",
      of: [{ type: "string" }],
      group: "story",
    }),
    defineField({
      name: "problem",
      title: "The problem",
      type: "array",
      of: [{ type: "block" }],
      group: "story",
      description: "What challenge did the client come to you with?",
    }),
    defineField({
      name: "process",
      title: "Creative process",
      type: "array",
      of: [{ type: "block" }, { type: "image", options: { hotspot: true } }],
      group: "story",
      description: "Walk through how you got from problem to solution.",
    }),
    defineField({
      name: "solution",
      title: "The solution",
      type: "array",
      of: [{ type: "block" }],
      group: "story",
    }),
    defineField({
      name: "toolsUsed",
      title: "Tools used",
      type: "array",
      of: [{ type: "string" }],
      group: "story",
    }),
    defineField({
      name: "brandStrategy",
      title: "Brand strategy notes",
      type: "array",
      of: [{ type: "block" }],
      group: "story",
    }),
    defineField({
      name: "typography",
      title: "Typography used",
      type: "array",
      of: [{ type: "string" }],
      group: "gallery",
    }),
    defineField({
      name: "colorPalette",
      title: "Color palette (hex codes)",
      type: "array",
      of: [{ type: "string" }],
      group: "gallery",
    }),
    defineField({
      name: "gallery",
      title: "Gallery images",
      type: "array",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [{ name: "alt", title: "Alt text", type: "string", validation: (r) => r.required() }],
        },
      ],
      group: "gallery",
    }),
    defineField({
      name: "beforeAfter",
      title: "Before / after images",
      type: "object",
      group: "gallery",
      fields: [
        { name: "before", title: "Before", type: "image", options: { hotspot: true } },
        { name: "after", title: "After", type: "image", options: { hotspot: true } },
      ],
    }),
    defineField({
      name: "results",
      title: "Results",
      type: "array",
      of: [{ type: "string" }],
      group: "results",
      description: "Measurable outcomes, e.g. '38% increase in social engagement in 60 days'.",
    }),
    defineField({
      name: "testimonial",
      title: "Client testimonial",
      type: "reference",
      to: [{ type: "testimonial" }],
      group: "results",
    }),
    defineField({
      name: "links",
      title: "Links",
      type: "object",
      group: "results",
      fields: [
        { name: "liveUrl", title: "Live URL", type: "url" },
        { name: "behance", title: "Behance", type: "url" },
        { name: "dribbble", title: "Dribbble", type: "url" },
        { name: "github", title: "GitHub", type: "url" },
      ],
    }),
  ],
  orderings: [
    {
      title: "Plate number",
      name: "plateAsc",
      by: [{ field: "plateNumber", direction: "asc" }],
    },
  ],
  preview: {
    select: { title: "title", subtitle: "client", media: "coverImage" },
  },
});
